services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cywolf\PageLinkInsights\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  Cywolf\PageLinkInsights\Controller\BackendController:
    tags: ['backend.controller']
    
  # Service explicitement configuré
  Cywolf\PageLinkInsights\Service\PageLinkService:
    public: true