services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cwolf\PageLinkInsights\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Cwolf\PageLinkInsights\Controller\BackendController:
    public: true