services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cwolf\PageLinkInsights\:
    resource: '../Classes/*'
    
  Cwolf\PageLinkInsights\Controller\BackendController:
    public: true
    arguments:
      $moduleTemplateFactory: '@TYPO3\CMS\Backend\Template\ModuleTemplateFactory'
      $pageRenderer: '@TYPO3\CMS\Core\Page\PageRenderer'
      $pageRepository: '@TYPO3\CMS\Core\Domain\Repository\PageRepository'
      $extensionConfiguration: '@TYPO3\CMS\Core\Configuration\ExtensionConfiguration'
      $pageLinkService: '@Cwolf\PageLinkInsights\Service\PageLinkService'