services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cywolf\PageLinkInsights\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  Cywolf\PageLinkInsights\Controller\BackendController:
    tags: ['backend.controller']
    
  Cywolf\PageLinkInsights\Service\PageLinkService:
    public: true

  Cywolf\PageLinkInsights\Service\PageMetricsService:
    public: true
    arguments:
      $pageLinkService: '@Cywolf\PageLinkInsights\Service\PageLinkService'

  Cywolf\PageLinkInsights\Task\AnalyzeLinksTask:
    public: true
    tags:
      - name: 'scheduler.task'
        title: 'LLL:EXT:page_link_insights/Resources/Private/Language/locallang.xlf:task.analyzeLinks.title'
        description: 'LLL:EXT:page_link_insights/Resources/Private/Language/locallang.xlf:task.analyzeLinks.description'
  
  Cywolf\PageLinkInsights\Service\ThemeDataService:
    public: true
    # Pas besoin de définir explicitement les arguments car autowire: true les gérera