services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cywolf\PageLinkInsights\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  Cywolf\PageLinkInsights\Controller\BackendController:
    tags: ['backend.controller']
    arguments:
      $moduleTemplateFactory: '@TYPO3\CMS\Backend\Template\ModuleTemplateFactory'
      $pageRenderer: '@TYPO3\CMS\Core\Page\PageRenderer'
      $extensionConfiguration: '@TYPO3\CMS\Core\Configuration\ExtensionConfiguration'
      $pageLinkService: '@Cywolf\PageLinkInsights\Service\PageLinkService'
      $themeDataService: '@Cywolf\PageLinkInsights\Service\ThemeDataService'
    
  Cywolf\PageLinkInsights\Service\PageLinkService:
    public: true

  Cywolf\PageLinkInsights\Service\PageMetricsService:
    public: true
    arguments:
      $pageLinkService: '@Cywolf\PageLinkInsights\Service\PageLinkService'

  Cywolf\PageLinkInsights\Task\AnalyzeLinksTask:
    public: true
    tags:
      - name: 'scheduler.task'
        title: 'LLL:EXT:page_link_insights/Resources/Private/Language/locallang.xlf:task.analyzeLinks.title'
        description: 'LLL:EXT:page_link_insights/Resources/Private/Language/locallang.xlf:task.analyzeLinks.description'
  
  Cywolf\PageLinkInsights\Service\ThemeDataService:
    public: true